FROM node:20-alpine

WORKDIR /app

# Copia apenas os arquivos de dependência
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia todo o código
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
